# Generated by Django 3.2.6 on 2021-09-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joined_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='login.User'),
        ),
    ]
